### ISSUE TITLE
Yarn v2 (berry) support

### ISSUE THREAD

**Issue by toastal** [twuni/asdf-yarn#12]
Currently we are on Yarn 1.22.x, which is the minor version that puts Yarn into maintenance mode. Yarn v2 (aka berry) is [already here](https://dev.to/arcanis/introducing-yarn-2-4eh1) and just came out of release candidate with its [first release](https://github.com/yarnpkg/berry/releases). For legacy reasons, the yarn team says it will keep the repository for v2 in this `berry` repo, however, the new binary is still `yarn`. 

This `asdf` plugin should ideally aggregate (in parallel) versions across the two `yarn` and `berry` repos, and download and install from the appropriate repository. Granted there would need to be a big fork in the shell scripts, for if the version is 2+, but as a user of the plugin I want the latest v2+ of `yarn`.

**Comment by canterberry** [comment]
Thanks for the heads-up!

Before getting started on Yarn 2.x, I'm reading through some of the documentation and the repo and I'm having some trouble understanding what to do in order to support Yarn 2.x with `asdf`.

 * The [releases](https://github.com/yarnpkg/berry/releases) in the berry repo are significantly more complex than that of the [v1 repo](https://github.com/yarnpkg/yarn/releases), and that *may* not be a viable strategy for checking which v2.x versions of Yarn are available.

 * The [install instructions](https://next.yarnpkg.com/getting-started/install) for Yarn v2.x suggest installing via `npm install -g yarn`, then on a per-project basis using `yarn set version ...` to adjust the version for that project. There does not seem to be a documented way of installing a particular version of Yarn v2.x, or listing the versions that are available.

These challenges are likely solvable, but seeing Yarn move in a direction of managing its own versions does negate (at least partially) the benefits of a unified version manager like asdf.

Specific questions to answer in order to move forward (open to anyone with the answers):

 * What is the Yarn team's preferred way for a tool like this one to (a) list available versions of Yarn v2.x, and (b) install a specific version of Yarn to a specific directory managed by the tool?

 * Is the latest v1.x release of Yarn possibly the latest version of Yarn this tool *should* install? Given that this version has the ability to enable Yarn v2.x on a per-project basis if configured to do so.

**Comment by canterberry** [comment]
Taking another look at the upstream documentation again, and re-reading the comment above, the observations above are still relevant. Thus, I'm closing this issue. Here's the rationale:

 1. Yarn still recommends installation globally via `npm install -g yarn`. Many users of `asdf` prefer it because it does not require global installation, so this plugin remains a viable alternative to performing this step.
 2. The latest version published to npm is currently 1.22.10, which aligns with the latest version available via this plugin.
 3. Yarn requires individual projects to opt-in to Yarn v2 using Yarn's own built-in version manager. As far as I can tell, Yarn v2 is only available through its own version management system, and it would be counter-productive for this plugin to interfere with that.

Thus, to use Yarn v2 in a project:
 1. Use this plugin to make Yarn available to the project (in **.tool-versions**, a line for `yarn 1.22.10`).
 2. Use `yarn set version ...` to configure which version the project should use. This, along with other Yarn configuration, is stored in the project's [**.yarn**](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored) directory.

**Comment by DilumAluthge** [comment]
> Thus, to use Yarn v2 in a project:
> 
>    1. Use this plugin to make Yarn available to the project (in **.tool-versions**, a line for `yarn 1.22.10`).
> 
>    2. Use `yarn set version ...` to configure which version the project should use. This, along with other Yarn configuration, is stored in the project's [**.yarn**](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored) directory.

Perhaps we could add this information to the `asdf-yarn` README?
