### ISSUE TITLE
Install not working properly

### ISSUE THREAD

**Issue by nolleto** [twuni/asdf-yarn#20]
Hello, I'm trying to install yarn by the command:
```cmd
$ asdf install yarn 1.22.4
```
And I get the following message:
> ⛔ Missing one of either of the following dependencies: wget, curl

I also tried install another yarn versions but I still get the same error message.

I'm currently using a Macbook and I have `curl` installed. I checked it by executing:
```cmd
curl --version
```

Hope someone can help me 😄

**Comment by canterberry** [comment]
That error message is coming from the following statement in this plugin's install script:

```sh
[ -x "$(which wget)" -o -x "$(which curl)" ]
```

To figure out what's happening, let's break that down into another script for debugging:

```sh
#!/usr/bin/env bash

WGET="$(which wget)"
CURL="$(which curl)"

echo "wget: ${WGET}"
echo "curl: ${CURL}"
```

If you copy/paste that into a new file, `chmod +x ...` the file (i.e: set its executable flag), then run it, I would expect this issue to be reproduced, showing nothing for either wget or curl.

Can you try that and paste the result here?

I'm also curious what is printed if you run `which curl` directly on the command-line (vs in the script). May be a PATH issue.

**Comment by nolleto** [comment]
This was the result @canterberry 
![image](https://user-images.githubusercontent.com/2437673/110472011-990df300-80bb-11eb-9c28-7a55e0678c98.png)

> wget: No such command in 14.15.1 of nodejs
curl: No such command in 14.15.1 of nodejs

I installed `curl` with npm by the command:
```cmd
npm install --global curl
```
But I'm still getting the same error
🤔

**Comment by nolleto** [comment]
Let me share with you this:
![image](https://user-images.githubusercontent.com/2437673/110472900-b2636f00-80bc-11eb-89bb-7abde8858de3.png)

**Comment by canterberry** [comment]
Thanks for sharing! I see two highly suspicious things in the output:

 1. `npm install --global curl` is not how to install curl. On Mac OS X, `curl` can be installed via [`brew install curl`](https://formulae.brew.sh/formula/curl#default). You have installed an errantly named npm package that may or may not be malicious (or at the least, intentionally misleading).

 2. `which` is a system command that, under no circumstances, should have any awareness of nodejs, much less any specific version of nodejs. It's very suspicious and strange that your output indicates that it trying to find those commands using some kind of path resolver with awareness of nodejs. Are you using any kind of specialized shell or terminal app, maybe? Different terminal apps may do all sorts of interesting things with the session!

I know it may not be helpful to suggest and could seem like overkill, but given what I'm seeing in the CLI output you've shared, it might be better to factory reset and start again from a known common state. Otherwise, we may end up spending a significant amount of time reverse-engineering all the possible things that could have impacted your system's binaries and/or shell environment.

If anyone else has advice to help, please chime in! I'm not as well informed on the variety of environments folks might be using, personally, but we've got a wide community here who may have much more insight to offer. I imagine other tools might be affected by this class of issue as well.

**Comment by canterberry** [comment]
Closing this issue as stale.

**Comment by FeanorsCurse** [comment]
Just fyi, was facing a similar issue. What helped was running `brew install wget curl gpg`. Might be useful to add that to the requirements (does indeed not seem to run out of the box, which is fine).

However, even then it's not working - not gonna create a new issue, just gonna install yarn manually, but fyi:

> --2024-01-05 10:36:10--  https://classic.yarnpkg.com/downloads/1.22.21/yarn-v1.22.21.tar.gz.asc
> Resolving classic.yarnpkg.com (classic.yarnpkg.com)... 2a05:d014:58f:6202::64, 2a05:d014:275:cb02::c8, 35.156.224.161, ...
> Connecting to classic.yarnpkg.com (classic.yarnpkg.com)|2a05:d014:58f:6202::64|:443... connected.
> HTTP request sent, awaiting response... 301 Moved Permanently
> Location: https://github.com/yarnpkg/yarn/releases/download/v1.22.21/yarn-v1.22.21.tar.gz.asc [following]
> --2024-01-05 10:36:10--  https://github.com/yarnpkg/yarn/releases/download/v1.22.21/yarn-v1.22.21.tar.gz.asc
> Resolving github.com (github.com)... 140.82.121.4
> Connecting to github.com (github.com)|140.82.121.4|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2024-01-05 10:36:10 ERROR 404: Not Found.

**Comment by iPurpl3x** [comment]
@FeanorsCurse I saw the artifacts are missing... I think it will be fixed at some point. Old versions work properly.
<img width="829" alt="image" src="https://github.com/twuni/asdf-yarn/assets/18526076/5c598016-5bf8-4e18-b533-30fdf08e6be3">

**Comment by canterberry** [comment]
@iPurpl3x See #33 . I reached out to the yarn maintainers about that issue. There's currently no momentum on the yarn side to get that fixed, so a volunteer would need to (a) step up to see that through, and (b) persuade the yarn maintainers to accept the contribution.
