### ISSUE TITLE
Support installing yarn berry directly

### ISSUE THREAD

**Issue by timdp** [twuni/asdf-yarn#21]
The readme explicitly describes installing Yarn v2 (and up, now that v3 is out) using classic. I understand that this is what the Yarn team likes, but it defeats the purpose of asdf. I don't see any point in locking down the version using two separate tools.

Therefore, have you considered or tried installing the latest version directly?

If not, would you accept a PR that adds this functionality?

**Comment by canterberry** [comment]
Sure! However, it's a little more complicated than it may seem on the surface because yarn is aware of its own version and wants to manage that exclusively.

It's very confusing the way things are now if you want yarn v2.x (or v3.x), because you'd use asdf to set the version to 1.22.10 and yarn's own config to set its own version to, say, 3.0.0.

Even if revising this plugin to manage yarn v3.x, yarn would still insist on its own version being declared in a yarn-readable way, in addition to in .tool-versions. I'd consider it an anti-pattern for this plugin to perform any modifications to files other than its designated plugin directories (i.e: to conform with a general expectation for asdf plugins to leave no trace).

See https://github.com/twuni/asdf-yarn/issues/12 for prior art and research.

If asdf and yarn can play nicely for version management v2.x and beyond, and the Yarn team is willing to support the strategy, I think the possibility of an asdf-managed yarn beyond 1.x could be a boon. If not, then asdf can currently, at least, be used to bootstrap the process.

**Comment by timdp** [comment]
I honestly don't know why I didn't find the original issue. At any rate, thanks for the elaborate response!

I totally see the complexity. And it gets all the more interesting if you also consider plugins.

I might still explore our options and document my findings, but I'll go ahead and close this issue as a duplicate.
