### ISSUE TITLE
command not found: yarn

### ISSUE THREAD

**Issue by williandandrade** [twuni/asdf-yarn#25]
Steps to reproduce:

* add plugin `asdf plugin-add yarn`
* .tool-versions with: `nodejs 16.13.0` and `yarn 1.22.17`
* `asdf install # OK`
* `yarn # command not found: yarn`

Environment:

```bash
asdf info

OS:
Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

SHELL:
zsh 5.8 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.9.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/opt/homebrew/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
nodejs                       ssh://git@github.com/asdf-vm/asdf-nodejs.git master 54113a9
yarn                         ssh://git@github.com/twuni/asdf-yarn.git main 376c540
```

**Comment by canterberry** [comment]
:thinking: Hmm, I haven't tried using `asdf install` with no additional arguments before. I just tried it in a fresh local directory with a .tool-versions containing a Yarn version I had not installed prior, and it worked for me.

```
$ asdf info
OS:
###REDACTED###

SHELL:
zsh 5.8 (x86_64-ubuntu-linux-gnu)

ASDF VERSION:
v0.9.0-9ee24a3

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=###REDACTED###

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 54113a9
yarn                         https://github.com/twuni/asdf-yarn.git main 376c540
```

Does `asdf install yarn 1.22.17` work for you? I'm wondering if maybe `asdf install` works differently on macOS when given no arguments. From what I can tell, all that is doing is enumerating the currently desired version of each installed plugin and calling that plugin's install script with the same parameters that would be given if invoking the `asdf install PLUGIN VERSION` command specifically for that plugin.

If `asdf install yarn 1.22.17` fails, then that would explain why the `yarn` command is unavailable afterward. If it *does* fail, the command output will help pin down the root cause.

**Comment by williandandrade** [comment]
`asdf install yarn 1.22.17` worked and the command is available.

```
which yarn # /Users/willian/.asdf/shims/yarn
```

I have no idea why `asdf install` didn't worked 🤔

**Comment by ospfranco** [comment]
I just faced the same issue. I tried afterwards to do `asdf install yarn 1.22.17` but it still doesn't work. I re-opened my terminal and still nothing. Any idea what could be going on?

Edit: nvm, found the problem I was missing the path on my `zshrc` file (. /opt/homebrew/opt/asdf/libexec/asdf.sh)
