### ISSUE TITLE
Hard to troubleshoot installation issues

### ISSUE THREAD

**Issue by kkrauth** [twuni/asdf-yarn#4]
It seems that all error messages are being swallowed which makes it impossible to troubleshoot installation problems. In my case it was an issue with the SSL handshake to github. I had to manually edit the plugin install script locally and remove this line:
https://github.com/twuni/asdf-yarn/blob/39715d2fae45d733060d457e3a3f4ce63c5d36cd/bin/install#L3

Other plugins seem to print debug information when they encounter issues, would be great if this one followed that standard too.

**Comment by canterberry** [comment]
Thanks for the report, @kkrauth! That sounds mega-frustrating. I run into similar issues with other plugins, so I know what you mean. That line, actually, is intended to short-circuit the script immediately if/when any errors occur. The real problem is, as you mentioned, that error message didn't appear in the command output. I'll see what I can do to, at least, log any errors to stderr before failing.

**Comment by canterberry** [comment]
Hey @kkrauth I opened PR #5 to resolve this.

This plugin attempts to use either `wget` or `curl`, depending on what is available (and detected in that order). The `curl` code path has the *silent* flag, but also has the *but still show errors* flag. The `wget` path, however, only had the *quiet* flag, so would have failed silently as you reported. I'm guessing you have `wget` available, which would have triggered the errant path.

**Comment by kkrauth** [comment]
That's correct! I ended up removing wget entirely since cURL was configured with the correct certs on my system, but I didn't spot the quiet flag parameter on the wget invocation. Thanks for addressing this!
